#!/bin/bash

echo "🚀 WhatsApp Ordering MVP - Cloud Deployment Setup"
echo ""
echo "Choose your deployment platform:"
echo ""
echo "1) Railway (Recommended - Free tier, 1-click GitHub)"
echo "2) Render (Free tier available)"
echo "3) Heroku (Free tier limited)"
echo "4) DigitalOcean (App Platform)"
echo ""
read -p "Enter your choice (1-4): " choice

case $choice in
  1)
    echo ""
    echo "🚄 Railway Setup"
    echo "==============="
    echo ""
    echo "Step 1: Push to GitHub"
    echo "  git remote add origin https://github.com/YOUR_USERNAME/whatsapp-ordering-mvp.git"
    echo "  git push -u origin main"
    echo ""
    echo "Step 2: Create Railway Account"
    echo "  Go to: https://railway.app"
    echo "  Sign up with GitHub"
    echo ""
    echo "Step 3: Connect Your Repository"
    echo "  Click 'New Project' → Select GitHub repo → Deploy"
    echo ""
    echo "Step 4: Set Environment Variables"
    echo "  In Railway Dashboard → Variables:"
    echo "    PORT=3000"
    echo "    WHATSAPP_API_TOKEN=your_token"
    echo "    WHATSAPP_VERIFY_TOKEN=your_verify_token"
    echo ""
    echo "✅ Your app will be live at: https://[project]-[env].railway.app"
    ;;
  2)
    echo ""
    echo "🎨 Render Setup"
    echo "==============="
    echo ""
    echo "Step 1: Push to GitHub (same as Railway)"
    echo ""
    echo "Step 2: Create Render Account"
    echo "  Go to: https://render.com"
    echo "  Sign up with GitHub"
    echo ""
    echo "Step 3: Create New Web Service"
    echo "  Connect GitHub → Select repo"
    echo "  Build: npm install"
    echo "  Start: npm start"
    echo ""
    echo "Step 4: Add Environment Variables"
    echo "  PORT=3000"
    echo "  WHATSAPP_API_TOKEN=your_token"
    echo "  WHATSAPP_VERIFY_TOKEN=your_verify_token"
    echo ""
    echo "✅ Your app will be live at: https://[project].onrender.com"
    ;;
  3)
    echo ""
    echo "🔧 Heroku Setup"
    echo "==============="
    echo ""
    echo "Step 1: Install Heroku CLI"
    echo "  brew tap heroku/brew && brew install heroku"
    echo ""
    echo "Step 2: Login to Heroku"
    echo "  heroku login"
    echo ""
    echo "Step 3: Create App"
    echo "  heroku create your-app-name"
    echo ""
    echo "Step 4: Set Environment Variables"
    echo "  heroku config:set WHATSAPP_API_TOKEN=your_token"
    echo "  heroku config:set WHATSAPP_VERIFY_TOKEN=your_verify_token"
    echo ""
    echo "Step 5: Deploy"
    echo "  git push heroku main"
    echo ""
    echo "✅ Your app will be live at: https://your-app-name.herokuapp.com"
    ;;
  4)
    echo ""
    echo "🌊 DigitalOcean Setup"
    echo "===================="
    echo ""
    echo "Step 1: Push to GitHub"
    echo ""
    echo "Step 2: Create DigitalOcean Account"
    echo "  Go to: https://digitalocean.com"
    echo ""
    echo "Step 3: Create App Platform"
    echo "  Apps → Create → GitHub"
    echo "  Select this repo"
    echo ""
    echo "Step 4: Configure Build"
    echo "  Build: npm install"
    echo "  Start: npm start"
    echo ""
    echo "Step 5: Add Environment Variables"
    echo ""
    echo "✅ Your app will be live in ~5 minutes"
    ;;
  *)
    echo "Invalid choice"
    ;;
esac
